using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using CommandLine;
using RazorEngine;
using RazorEngine.Templating;
using SignalrTypescriptGenerator.Models;
using Encoding = System.Text.Encoding;

namespace SignalrTypescriptGenerator
{
	class Program
	{
		static int Main(string[] args)
		{
			if (AppDomain.CurrentDomain.IsDefaultAppDomain())
			{
				return RunInNewAppDomainToAllowRazorEngineToCleanup(args);
			}

			try
			{
				return Parser.Default.ParseArguments<CommandLineOptions>(args)
					.MapResult(options =>
					{
						Run(options);
						return 0;
					},
					errors => 1);
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}

		static int RunInNewAppDomainToAllowRazorEngineToCleanup(string[] args)
		{
			var appDomain = AppDomain.CreateDomain("RazorEngine", null, AppDomain.CurrentDomain.SetupInformation);
			var exitCode = appDomain.ExecuteAssembly(Assembly.GetExecutingAssembly().Location, args);
			AppDomain.Unload(appDomain);
			return exitCode;
		}

		static void Run(CommandLineOptions commandLineOptions)
		{
			var signalrHelper = new SignalrHubinator(commandLineOptions.AssemblyPath);

			var model = new TypesModel();
			model.Hubs = signalrHelper.GetHubs();
			model.ServiceContracts = signalrHelper.GetServiceContracts();
			model.Clients = signalrHelper.GetClients();
			model.DataContracts = signalrHelper.GetDataContracts();
			model.Enums = signalrHelper.GetEnums();

			string template = ReadEmbeddedFile("template.cshtml");
			string outputText = Engine.Razor.RunCompile(template, "templateKey", null, model);

			if (!string.IsNullOrEmpty(commandLineOptions.OutFile))
			{
				if (FileHasChanged(commandLineOptions.OutFile, outputText))
				{
					outputText = model.LastGenerated + Environment.NewLine + outputText;
					File.WriteAllText(commandLineOptions.OutFile, outputText);
				}
			}
			else
			{
				outputText = model.LastGenerated + Environment.NewLine + outputText;
				Console.WriteLine(outputText);
			}
		}

		static bool FileHasChanged(string filename, string contents)
		{
			string currentContents = File.Exists(filename) ? File.ReadAllText(filename) : string.Empty;

			// Remove the timestamp
			int startIndex = currentContents.IndexOf("// Autogenerated", StringComparison.Ordinal);
			if (startIndex > -1)
			{
				int endIndex = currentContents.IndexOf(Environment.NewLine, startIndex, StringComparison.Ordinal);
				if (endIndex > startIndex)
				{
					currentContents = currentContents.Substring(endIndex + Environment.NewLine.Length);
				}
			}

			string currentHash = GetMd5(currentContents);
			string newHash = GetMd5(contents);
			Console.WriteLine("[SignalrTypescriptGenerator] Existing MD5 for {0}: {1}", filename, currentHash);
			Console.WriteLine("[SignalrTypescriptGenerator] New MD5: {0}", newHash);

			bool hashesAreDifferent = (currentHash != newHash);
			Console.WriteLine("[SignalrTypescriptGenerator] (content is {0})", hashesAreDifferent ? "different - generating new file" : "the same - skipping file generation.");

			return hashesAreDifferent;
		}

		static string GetMd5(string contents)
		{
			using (var md5 = MD5.Create())
			{
				using (var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(contents)))
				{
					var hash = md5.ComputeHash(memoryStream);

				    StringBuilder result = new StringBuilder();
				    foreach (byte b in hash)
				        result = result.Append(b.ToString("x2"));

				    return result.ToString();
				}
			}
		}

		static string ReadEmbeddedFile(string file)
		{
			string resourcePath = string.Format("{0}.{1}", typeof(Program).Namespace, file);

			Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourcePath);
			if (stream == null)
				throw new InvalidOperationException(string.Format("Unable to find '{0}' as an embedded resource", resourcePath));

			string textContent = "";
			using (StreamReader reader = new StreamReader(stream))
			{
				textContent = reader.ReadToEnd();
			}

			return textContent;
		}
	}
}
